### ISSUE TITLE
that cause problem with wave progression

### ISSUE THREAD

**Issue by Chtidino** [Cryotheus/nzombies_record_tracker#2]
22/03/2020 17:25:13: Lua Error: [nZombies Wave Record Tracker] lua/autorun/nz_record_tracker.lua:43: bad argument #1 to 'WriteUInt' (number expected, got nil) 1. WriteUInt - [C]:-1 2. congratulate_players - lua/autorun/nz_record_tracker.lua:43 3. fn - lua/autorun/nz_record_tracker.lua:123 4. Call - addons/ulib/lua/ulib/shared/hook.lua:109 5. Prepare - addons/nzombies-master-workshop-fr/gamemodes/nzombies/gamemode/round/sv_round.lua:49 6. Think - addons/nzombies-master-workshop-fr/gamemodes/nzombies/gamemode/round/sv_round.lua:355 7. unknown - addons/nzombies-master-workshop-fr/gamemodes/nzombies/gamemode/round/sv_round.lua:304 [nZombies Wave Record Tracker] lua/autorun/nz_record_tracker.lua:43: bad argument #1 to 'WriteUInt' (number expected, got nil) 1. WriteUInt - [C]:-1 2. congratulate_players - lua/autorun/nz_record_tracker.lua:43 3. fn - lua/autorun/nz_record_tracker.lua:123 4. Call - addons/ulib/lua/ulib/shared/hook.lua:109 5. Prepare - addons/nzombies-master-workshop-fr/gamemodes/nzombies/gamemode/round/sv_round.lua:49 6. Think - addons/nzombies-master-workshop-fr/gamemodes/nzombies/gamemode/round/sv_round.lua:355 7. unknown - addons/nzombies-master-workshop-fr/gamemodes/nzombies/gamemode/round/sv_round.lua:304 Timer Failed! [NZRoundThink][@addons/nzombies-master-workshop-fr/gamemodes/nzombies/gamemode/round/sv_round.lua (line 304)]

**Comment by Cryotheus** [comment]
Issue has been resolved as commit [6d7fcaa03b46c442cae73be91a9a01adfcc13930].(https://github.com/Cryotheus/nzombies_record_tracker/commit/6d7fcaa03b46c442cae73be91a9a01adfcc13930)
